name: Deploy to GitHub Pages

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'

    - name: Remove node_modules
      run: rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build --prod

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/liquid-prep-app
        publish_branch: deploy
        force_orphan: true